### ISSUE TITLE
compile errors on build

### ISSUE THREAD

**Issue by blythed** [diux-dev/ncluster#20]
Hi, Have you tested with ubuntu 16.04?

I get this build error:

"Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-webznc5h/pynacl/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e7lenchi-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-webznc5h/pynacl/"

**Comment by yaroslavvb** [comment]
yes, I do everything on Ubuntu 16....this error is not referencing anything in ncluster, perhaps try to recreate a new Python env
