### ISSUE TITLE
support for faster default EBS

### ISSUE THREAD

**Issue by yaroslavvb** [diux-dev/ncluster#3]

**Comment by yaroslavvb** [comment]
This is enabled with `NCLUSTER_AWS_FAST_ROOTDISK` env var

**Comment by kbhardwa** [comment]
Can you please provide more detail on what this parameter actually does?

**Comment by yaroslavvb** [comment]
it increases number of IOPS available on root disk. For more information see reply of AWS support

---
The IOPS for EBS, gp2 type volumes, which I see you are currently using are dependent on the size of the volume. As the IOPS are directly related to the volume size, the baseline performance scales linearly at 3 IOPS per GiB of volume size. This means that in order to increase the IOPS for a GP2 type EBS Volume the size will need to be increased and need to be resized within the instance. While the baseline IOPS is based on the size, you have a burstable IOPS of up to 3000 IOPS. For more information please see this documentation [1].

 - For example; A gp2 type EBS Volume, at the size of 100GB will have 300 IOPS, if you want to increase the IOPS to 1500 IOPS, you will need to modify the volume and increase the size to 500GiB.
 
If you would like the freedom of increasing the IOPS on your volume without having to increase the size, you can modify your Volume Type to IO1. Unlike gp2 which is a general purpose SSD, the IO1 Volume type is a provisioned IOPS SSD volume. This will allow you to increase and set your desired IOPS to a 50:1 ratio of the volume size. 
Changing the volume type does not require you to reboot the instance. Please do keep in mind that Provisioned IOPS are billed separately from the Volume Size [2].

 - For example; An IO1 type EBS volume, at the size of 100GB can have up to 5000 IOPS. 
 
This guide will provide more information on how to modify your volume type, size or IOPS [3] and resize within your Linux OS [4]. (Quick Guide: AWS Console - Volumes - Right Click on your Volume - Modify - Change Volume Type, size, IOPS)

To answer your second question, the 1500/3000 IOPS indicates that your current baseline IOPS is 1500 IOPS and a burstable IOPS count of up to 3000 IOPS, this will be true for the volume type gp2 and size of 500GiB.

Do take in consideration that the Instance type also has a maximum bandwidth and this can bottleneck your EBS Volume IOPS. Upgrading your Instance to an EBS Optimized Instance type will insure you that you can utilize the full capacity of your EBS Volume IOPS.

 - Please see this link on EBS-Optimized Instances [5]. 

This link will provide a more in-depth guide on how to benchmark your EBS Volumes performance [6]. 
 
I hope that the above information helps answer your questions, please do not hesitate to ask if you have any further questions or need any further assistance. I will be more than happy to assist.

Reference Links:
- [1] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html  
- [2] https://aws.amazon.com/ebs/pricing/
- [3] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/console-modify.html 
- [4] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.html
- [5] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html
- [6] https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/benchmark_procedures.html

**Comment by kbhardwa** [comment]
Great. Thanks a lot. This clarifies my question.
